[package]
name = "nelomai-app"
version = "0.1.1"
description = "Native Nelomai client"
authors = ["Nelomai"]
edition = "2021"
rust-version = "1.88"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "nelomai_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
async-trait = "0.1"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-tunnel-android = { path = "../plugins/tunnel-android" }
nelomai-client-api = { path = "../crates/client-api" }
nelomai-client-application = { path = "../crates/client-application" }
nelomai-client-core = { path = "../crates/client-core" }
nelomai-client-storage = { path = "../crates/client-storage" }
nelomai-client-tunnel = { path = "../crates/client-tunnel" }
nelomai-client-updater = { path = "../crates/client-updater" }
nelomai-contracts = { path = "../crates/contracts" }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "time"] }

[target.'cfg(windows)'.dependencies]
nelomai-windows-service = { path = "../crates/windows-service" }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2"
nelomai-unix-service = { path = "../crates/unix-service" }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
tauri-plugin-updater = "=2.10.1"
