[package]
name = "tauri-plugin-push-android"
version = "0.1.0"
authors = ["Nelomai"]
description = "Firebase Cloud Messaging bridge for Nelomai Android"
edition = "2021"
rust-version = "1.88"
links = "tauri-plugin-push-android"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.11.3" }
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.6.3", features = ["build"] }
