pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        google()
    }
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case "com.android.library":
                    useVersion("8.0.2")
                    break
                case "org.jetbrains.kotlin.android":
                    useVersion("1.8.20")
                    break
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()

    }
}

include ':tauri-android'
include ':amneziawg-tunnel'
project(':amneziawg-tunnel').projectDir = new File(rootDir, '../../amneziawg-android-tunnel')
def tauriAndroidProjectDir = System.getenv('TAURI_ANDROID_PROJECT_DIR')
project(':tauri-android').projectDir = tauriAndroidProjectDir
    ? new File(tauriAndroidProjectDir)
    : new File('./.tauri/tauri-api')
